# Generated by Django 3.2.16 on 2023-03-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPSData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(max_length=40)),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=7)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=7)),
                ('altitude', models.IntegerField(max_length=3)),
                ('sattelites', models.IntegerField(max_length=3)),
                ('speed', models.IntegerField(max_length=4)),
            ],
        ),
    ]
