# Generated by Django 3.2.16 on 2023-03-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpsdata',
            name='altitude',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='sattelites',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='speed',
            field=models.IntegerField(),
        ),
    ]
