# Generated by Django 3.2.16 on 2023-03-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps_tracker', '0002_auto_20230303_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpsdata',
            name='latitude',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='longitude',
            field=models.CharField(max_length=255),
        ),
    ]
