# Generated by Django 3.2.16 on 2023-03-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps_tracker', '0003_auto_20230303_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
